
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Sep 20 2025 12:17:34 IST (Sep 20 2025 06:47:34 UTC)

// Verification Directory fv/fft8_f32_stream 

module fft8_f32_stream(clk, rst_n, s_valid, s_ready, s_real, s_imag,
     m_valid, m_ready, m_real, m_imag);
  input clk, rst_n, s_valid, m_ready;
  input [31:0] s_real, s_imag;
  output s_ready, m_valid;
  output [31:0] m_real, m_imag;
  wire clk, rst_n, s_valid, m_ready;
  wire [31:0] s_real, s_imag;
  wire s_ready, m_valid;
  wire [31:0] m_real, m_imag;
  wire [2:0] wr_idx;
  wire fill_sel, full_A, full_B, n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_10, n_11, n_12, n_14;
  wire n_18, n_19;
  assign m_imag[0] = 1'b0;
  assign m_imag[1] = 1'b0;
  assign m_imag[2] = 1'b0;
  assign m_imag[3] = 1'b0;
  assign m_imag[4] = 1'b0;
  assign m_imag[5] = 1'b0;
  assign m_imag[6] = 1'b0;
  assign m_imag[7] = 1'b0;
  assign m_imag[8] = 1'b0;
  assign m_imag[9] = 1'b0;
  assign m_imag[10] = 1'b0;
  assign m_imag[11] = 1'b0;
  assign m_imag[12] = 1'b0;
  assign m_imag[13] = 1'b0;
  assign m_imag[14] = 1'b0;
  assign m_imag[15] = 1'b0;
  assign m_imag[16] = 1'b0;
  assign m_imag[17] = 1'b0;
  assign m_imag[18] = 1'b0;
  assign m_imag[19] = 1'b0;
  assign m_imag[20] = 1'b0;
  assign m_imag[21] = 1'b0;
  assign m_imag[22] = 1'b0;
  assign m_imag[23] = 1'b0;
  assign m_imag[24] = 1'b0;
  assign m_imag[25] = 1'b0;
  assign m_imag[26] = 1'b0;
  assign m_imag[27] = 1'b0;
  assign m_imag[28] = 1'b0;
  assign m_imag[29] = 1'b0;
  assign m_imag[30] = 1'b0;
  assign m_imag[31] = 1'b0;
  assign m_real[0] = 1'b0;
  assign m_real[1] = 1'b0;
  assign m_real[2] = 1'b0;
  assign m_real[3] = 1'b0;
  assign m_real[4] = 1'b0;
  assign m_real[5] = 1'b0;
  assign m_real[6] = 1'b0;
  assign m_real[7] = 1'b0;
  assign m_real[8] = 1'b0;
  assign m_real[9] = 1'b0;
  assign m_real[10] = 1'b0;
  assign m_real[11] = 1'b0;
  assign m_real[12] = 1'b0;
  assign m_real[13] = 1'b0;
  assign m_real[14] = 1'b0;
  assign m_real[15] = 1'b0;
  assign m_real[16] = 1'b0;
  assign m_real[17] = 1'b0;
  assign m_real[18] = 1'b0;
  assign m_real[19] = 1'b0;
  assign m_real[20] = 1'b0;
  assign m_real[21] = 1'b0;
  assign m_real[22] = 1'b0;
  assign m_real[23] = 1'b0;
  assign m_real[24] = 1'b0;
  assign m_real[25] = 1'b0;
  assign m_real[26] = 1'b0;
  assign m_real[27] = 1'b0;
  assign m_real[28] = 1'b0;
  assign m_real[29] = 1'b0;
  assign m_real[30] = 1'b0;
  assign m_real[31] = 1'b0;
  assign m_valid = 1'b0;
  SDFFRHQX1 fill_sel_reg(.RN (rst_n), .CK (clk), .D (n_12), .SI
       (fill_sel), .SE (n_14), .Q (fill_sel));
  SDFFRHQX1 \wr_idx_reg[1] (.RN (rst_n), .CK (clk), .D (n_19), .SI
       (wr_idx[1]), .SE (n_18), .Q (wr_idx[1]));
  NAND2BX1 g1143__2398(.AN (n_10), .B (wr_idx[2]), .Y (n_14));
  NAND2BX1 g1144__5107(.AN (n_18), .B (wr_idx[1]), .Y (n_10));
  NAND2BX1 g1145__6260(.AN (n_11), .B (s_ready), .Y (n_18));
  OAI22X1 g1146__4319(.A0 (full_A), .A1 (fill_sel), .B0 (full_B), .B1
       (n_12), .Y (s_ready));
  NAND2XL g1147__8428(.A (wr_idx[0]), .B (s_valid), .Y (n_11));
  INVXL g1148(.A (wr_idx[1]), .Y (n_19));
  INVX1 g1149(.A (fill_sel), .Y (n_12));
  DFFRHQX1 full_B_reg(.RN (rst_n), .CK (clk), .D (n_0), .Q (full_B));
  DFFRHQX1 \wr_idx_reg[0] (.RN (rst_n), .CK (clk), .D (n_7), .Q
       (wr_idx[0]));
  OAI21X1 g1200__5526(.A0 (fill_sel), .A1 (n_4), .B0 (n_2), .Y (n_8));
  DFFRHQX1 \wr_idx_reg[2] (.RN (rst_n), .CK (clk), .D (n_6), .Q
       (wr_idx[2]));
  NOR2BX1 g1202__6783(.AN (n_18), .B (n_3), .Y (n_7));
  OA21XL g1203__3680(.A0 (wr_idx[2]), .A1 (n_1), .B0 (n_14), .Y (n_6));
  INVX1 g1204(.A (n_4), .Y (n_5));
  AOI21X1 g1205__1617(.A0 (s_ready), .A1 (s_valid), .B0 (wr_idx[0]), .Y
       (n_3));
  NAND3BX1 g1206__2802(.AN (n_11), .B (wr_idx[2]), .C (wr_idx[1]), .Y
       (n_4));
  INVXL g1208(.A (n_10), .Y (n_1));
  AO21X1 g2__1705(.A0 (fill_sel), .A1 (n_5), .B0 (full_B), .Y (n_0));
  DFFRX1 full_A_reg(.RN (rst_n), .CK (clk), .D (n_8), .Q (full_A), .QN
       (n_2));
endmodule

