
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Sep 20 2025 12:04:12 IST (Sep 20 2025 06:34:12 UTC)

// Verification Directory fv/fft8_f32_stream 

module fft8_f32_stream(clk, rst_n, s_valid, s_ready, s_real, s_imag,
     m_valid, m_ready, m_real, m_imag);
  input clk, rst_n, s_valid, m_ready;
  input [31:0] s_real, s_imag;
  output s_ready, m_valid;
  output [31:0] m_real, m_imag;
  wire clk, rst_n, s_valid, m_ready;
  wire [31:0] s_real, s_imag;
  wire s_ready, m_valid;
  wire [31:0] m_real, m_imag;
  wire [2:0] wr_idx;
  wire fill_sel, full_A, full_B, n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14;
  assign m_imag[0] = 1'b0;
  assign m_imag[1] = 1'b0;
  assign m_imag[2] = 1'b0;
  assign m_imag[3] = 1'b0;
  assign m_imag[4] = 1'b0;
  assign m_imag[5] = 1'b0;
  assign m_imag[6] = 1'b0;
  assign m_imag[7] = 1'b0;
  assign m_imag[8] = 1'b0;
  assign m_imag[9] = 1'b0;
  assign m_imag[10] = 1'b0;
  assign m_imag[11] = 1'b0;
  assign m_imag[12] = 1'b0;
  assign m_imag[13] = 1'b0;
  assign m_imag[14] = 1'b0;
  assign m_imag[15] = 1'b0;
  assign m_imag[16] = 1'b0;
  assign m_imag[17] = 1'b0;
  assign m_imag[18] = 1'b0;
  assign m_imag[19] = 1'b0;
  assign m_imag[20] = 1'b0;
  assign m_imag[21] = 1'b0;
  assign m_imag[22] = 1'b0;
  assign m_imag[23] = 1'b0;
  assign m_imag[24] = 1'b0;
  assign m_imag[25] = 1'b0;
  assign m_imag[26] = 1'b0;
  assign m_imag[27] = 1'b0;
  assign m_imag[28] = 1'b0;
  assign m_imag[29] = 1'b0;
  assign m_imag[30] = 1'b0;
  assign m_imag[31] = 1'b0;
  assign m_real[0] = 1'b0;
  assign m_real[1] = 1'b0;
  assign m_real[2] = 1'b0;
  assign m_real[3] = 1'b0;
  assign m_real[4] = 1'b0;
  assign m_real[5] = 1'b0;
  assign m_real[6] = 1'b0;
  assign m_real[7] = 1'b0;
  assign m_real[8] = 1'b0;
  assign m_real[9] = 1'b0;
  assign m_real[10] = 1'b0;
  assign m_real[11] = 1'b0;
  assign m_real[12] = 1'b0;
  assign m_real[13] = 1'b0;
  assign m_real[14] = 1'b0;
  assign m_real[15] = 1'b0;
  assign m_real[16] = 1'b0;
  assign m_real[17] = 1'b0;
  assign m_real[18] = 1'b0;
  assign m_real[19] = 1'b0;
  assign m_real[20] = 1'b0;
  assign m_real[21] = 1'b0;
  assign m_real[22] = 1'b0;
  assign m_real[23] = 1'b0;
  assign m_real[24] = 1'b0;
  assign m_real[25] = 1'b0;
  assign m_real[26] = 1'b0;
  assign m_real[27] = 1'b0;
  assign m_real[28] = 1'b0;
  assign m_real[29] = 1'b0;
  assign m_real[30] = 1'b0;
  assign m_real[31] = 1'b0;
  assign m_valid = 1'b0;
  SDFFRHQX1 fill_sel_reg(.RN (rst_n), .CK (clk), .D (n_0), .SI
       (fill_sel), .SE (n_13), .Q (fill_sel));
  DFFRHQX1 \wr_idx_reg[2] (.RN (rst_n), .CK (clk), .D (n_14), .Q
       (wr_idx[2]));
  OA21X1 g375__2398(.A0 (wr_idx[2]), .A1 (n_12), .B0 (n_13), .Y (n_14));
  NAND2XL g377__5107(.A (n_12), .B (wr_idx[2]), .Y (n_13));
  AOI21XL g378__6260(.A0 (n_8), .A1 (n_9), .B0 (n_12), .Y (n_11));
  DFFRHQX1 \wr_idx_reg[0] (.RN (rst_n), .CK (clk), .D (n_10), .Q
       (wr_idx[0]));
  OA21X1 g385__4319(.A0 (wr_idx[0]), .A1 (n_7), .B0 (n_9), .Y (n_10));
  NOR2XL g380__8428(.A (n_8), .B (n_9), .Y (n_12));
  NAND2XL g386__5526(.A (n_7), .B (wr_idx[0]), .Y (n_9));
  DFFRHQX1 full_A_reg(.RN (rst_n), .CK (clk), .D (n_4), .Q (full_A));
  DFFRHQX1 full_B_reg(.RN (rst_n), .CK (clk), .D (n_5), .Q (full_B));
  AND2X1 g387__6783(.A (s_valid), .B (s_ready), .Y (n_7));
  AO21X1 g384__3680(.A0 (n_1), .A1 (n_3), .B0 (full_B), .Y (n_5));
  AO21X1 g383__1617(.A0 (n_2), .A1 (n_3), .B0 (full_A), .Y (n_4));
  OR2X1 g389__2802(.A (n_2), .B (n_1), .Y (s_ready));
  NOR2XL g391__1705(.A (full_B), .B (n_0), .Y (n_1));
  AND4X1 g388__5122(.A (s_valid), .B (wr_idx[2]), .C (wr_idx[0]), .D
       (wr_idx[1]), .Y (n_3));
  NOR2XL g390__8246(.A (full_A), .B (fill_sel), .Y (n_2));
  INVXL g393(.A (fill_sel), .Y (n_0));
  DFFRX1 \wr_idx_reg[1] (.RN (rst_n), .CK (clk), .D (n_11), .Q
       (wr_idx[1]), .QN (n_8));
endmodule

