
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Aug 21 2025 15:24:55 IST (Aug 21 2025 09:54:55 UTC)

// Verification Directory fv/vedic_8x8_pipelined_spst 

module vedic_8x8_pipelined_spst(clk, rst, a, b, valid_i, product,
     valid_o);
  input clk, rst, valid_i;
  input [7:0] a, b;
  output [15:0] product;
  output valid_o;
  wire clk, rst, valid_i;
  wire [7:0] a, b;
  wire [15:0] product;
  wire valid_o;
  wire [7:0] b_reg1;
  wire [7:0] a_reg1;
  wire [15:0] partial1;
  wire [15:0] partial2;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, WALLACE_CSA_DUMMY_OP_groupi_n_0,
       WALLACE_CSA_DUMMY_OP_groupi_n_1,
       WALLACE_CSA_DUMMY_OP_groupi_n_2,
       WALLACE_CSA_DUMMY_OP_groupi_n_3,
       WALLACE_CSA_DUMMY_OP_groupi_n_5,
       WALLACE_CSA_DUMMY_OP_groupi_n_8, WALLACE_CSA_DUMMY_OP_groupi_n_9;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_10,
       WALLACE_CSA_DUMMY_OP_groupi_n_11,
       WALLACE_CSA_DUMMY_OP_groupi_n_12,
       WALLACE_CSA_DUMMY_OP_groupi_n_13,
       WALLACE_CSA_DUMMY_OP_groupi_n_14,
       WALLACE_CSA_DUMMY_OP_groupi_n_15,
       WALLACE_CSA_DUMMY_OP_groupi_n_16,
       WALLACE_CSA_DUMMY_OP_groupi_n_19;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_20,
       WALLACE_CSA_DUMMY_OP_groupi_n_21,
       WALLACE_CSA_DUMMY_OP_groupi_n_23,
       WALLACE_CSA_DUMMY_OP_groupi_n_24,
       WALLACE_CSA_DUMMY_OP_groupi_n_25,
       WALLACE_CSA_DUMMY_OP_groupi_n_26,
       WALLACE_CSA_DUMMY_OP_groupi_n_27,
       WALLACE_CSA_DUMMY_OP_groupi_n_28;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_29,
       WALLACE_CSA_DUMMY_OP_groupi_n_30,
       WALLACE_CSA_DUMMY_OP_groupi_n_31,
       WALLACE_CSA_DUMMY_OP_groupi_n_33,
       WALLACE_CSA_DUMMY_OP_groupi_n_34,
       WALLACE_CSA_DUMMY_OP_groupi_n_35,
       WALLACE_CSA_DUMMY_OP_groupi_n_36,
       WALLACE_CSA_DUMMY_OP_groupi_n_37;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_38,
       WALLACE_CSA_DUMMY_OP_groupi_n_39,
       WALLACE_CSA_DUMMY_OP_groupi_n_40,
       WALLACE_CSA_DUMMY_OP_groupi_n_41,
       WALLACE_CSA_DUMMY_OP_groupi_n_42,
       WALLACE_CSA_DUMMY_OP_groupi_n_44,
       WALLACE_CSA_DUMMY_OP_groupi_n_45,
       WALLACE_CSA_DUMMY_OP_groupi_n_46;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_47,
       WALLACE_CSA_DUMMY_OP_groupi_n_50,
       WALLACE_CSA_DUMMY_OP_groupi_n_51,
       WALLACE_CSA_DUMMY_OP_groupi_n_52,
       WALLACE_CSA_DUMMY_OP_groupi_n_53,
       WALLACE_CSA_DUMMY_OP_groupi_n_54,
       WALLACE_CSA_DUMMY_OP_groupi_n_55,
       WALLACE_CSA_DUMMY_OP_groupi_n_56;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_57,
       WALLACE_CSA_DUMMY_OP_groupi_n_58,
       WALLACE_CSA_DUMMY_OP_groupi_n_59,
       WALLACE_CSA_DUMMY_OP_groupi_n_60,
       WALLACE_CSA_DUMMY_OP_groupi_n_61,
       WALLACE_CSA_DUMMY_OP_groupi_n_64,
       WALLACE_CSA_DUMMY_OP_groupi_n_65,
       WALLACE_CSA_DUMMY_OP_groupi_n_66;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_68,
       WALLACE_CSA_DUMMY_OP_groupi_n_69,
       WALLACE_CSA_DUMMY_OP_groupi_n_70,
       WALLACE_CSA_DUMMY_OP_groupi_n_71,
       WALLACE_CSA_DUMMY_OP_groupi_n_72,
       WALLACE_CSA_DUMMY_OP_groupi_n_73,
       WALLACE_CSA_DUMMY_OP_groupi_n_76,
       WALLACE_CSA_DUMMY_OP_groupi_n_77;
  wire WALLACE_CSA_DUMMY_OP_groupi_n_78,
       WALLACE_CSA_DUMMY_OP_groupi_n_79,
       WALLACE_CSA_DUMMY_OP_groupi_n_80,
       WALLACE_CSA_DUMMY_OP_groupi_n_82,
       WALLACE_CSA_DUMMY_OP_groupi_n_83,
       WALLACE_CSA_DUMMY_OP_groupi_n_84, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_95, n_96, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_161, n_162, n_163, n_164;
  wire n_167, n_168, n_169, n_170, n_171, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_190, n_191, n_192, n_195, n_198;
  wire n_199, n_200, n_201, n_202, n_204, n_205, n_206, n_208;
  wire n_209, n_210, n_212, n_213, n_214, n_215, n_217, n_221;
  wire n_222, n_223, n_224, n_225, n_226, n_228, n_229, n_232;
  wire n_233, n_234, n_235, n_236, n_238, n_239, n_240, n_241;
  wire n_242, n_243, n_245, n_246, n_247, n_251, n_252, n_253;
  wire n_254, n_255, n_256, n_258, n_259, n_263, n_264, n_265;
  wire n_266, n_267, n_268, n_269, n_270, n_271, n_273, n_274;
  wire n_275, n_277, n_278, n_279, n_280, n_281, n_282, n_283;
  wire n_284, n_285, n_286, n_288, n_289, n_291, n_292, n_293;
  wire n_294, n_295, n_296, n_297, n_298, n_299, n_300, n_301;
  wire n_303, n_304, n_305, n_306, n_307, n_308, n_309, n_310;
  wire n_312, n_313, n_314, n_315, n_316, n_317, n_318, n_319;
  wire n_320, n_321, n_322, n_323, n_327, n_328, n_329, n_330;
  wire n_331, n_332, n_333, n_334, n_335, n_336, n_337, n_338;
  wire n_339, n_340, n_341, n_342, n_343, n_344, n_345, n_346;
  wire n_347, n_348, n_349, n_350, n_351, n_353, n_355, n_357;
  wire n_358, n_359, n_360, n_361, n_362, n_364, n_365, n_366;
  wire n_367, n_368, n_369, n_370, n_371, n_372, n_373, n_374;
  wire n_375, n_376, n_377, n_378, n_380, n_382, n_383, n_384;
  wire n_385, n_386, n_387, n_388, n_389, n_390, n_391, n_392;
  wire n_393, n_418, n_422, n_423, n_426, n_428, n_433, n_437;
  wire n_438, n_440, n_441, n_443, n_444, n_448, n_450, n_451;
  wire n_460, n_471, n_475, n_480, n_493, n_494, n_497, n_498;
  wire n_502, n_507, n_508, n_509, n_512, n_513, n_518, n_521;
  wire n_524, n_528, n_529, n_530, n_531, n_532, n_534, n_535;
  wire n_537, n_539, n_543, n_547, n_548, n_549, n_551, n_552;
  wire n_554, n_559, n_560, n_561, n_562, n_566, n_581, n_584;
  wire n_592, n_594, n_600, n_601, n_603, n_604, n_605, n_608;
  wire n_609, n_611, n_612, n_621, n_622, n_625, n_626, n_627;
  wire n_629, n_631, n_634, n_639, n_640, n_642, n_644, n_645;
  wire n_646, n_648, n_649, valid_stage1, valid_stage2;
  MXI2X1 g3859__2398(.A (n_348), .B (n_355), .S0 (n_338), .Y (n_362));
  OAI21X1 g3860__5107(.A0 (n_340), .A1 (n_350), .B0 (n_353), .Y
       (n_378));
  INVX1 g3863(.A (n_348), .Y (n_355));
  NAND2XL g3865__5526(.A (n_340), .B (n_350), .Y (n_353));
  OAI21X1 g3867__6783(.A0 (n_283), .A1 (n_345), .B0 (n_278), .Y
       (n_380));
  OAI21X1 g3868__3680(.A0 (n_267), .A1 (n_346), .B0 (n_277), .Y
       (n_364));
  OAI21X2 g3869__1617(.A0 (n_321), .A1 (n_512), .B0 (n_346), .Y
       (n_351));
  OAI21X1 g3870__2802(.A0 (n_332), .A1 (n_322), .B0 (n_330), .Y
       (n_350));
  AOI2BB1X1 g3871__1705(.A0N (n_331), .A1N (n_322), .B0 (n_344), .Y
       (n_349));
  XNOR2X1 g3872__5122(.A (n_149), .B (n_341), .Y (n_370));
  OAI21X1 g3873__8246(.A0 (n_322), .A1 (n_339), .B0 (n_347), .Y
       (n_377));
  OAI22X2 g3874__7098(.A0 (n_300), .A1 (n_342), .B0 (n_299), .B1
       (n_343), .Y (n_371));
  OAI21X2 g3876__6131(.A0 (n_321), .A1 (n_335), .B0 (n_333), .Y
       (n_348));
  NAND2XL g3877__1881(.A (n_322), .B (n_339), .Y (n_347));
  OAI21X2 g3878__5115(.A0 (n_281), .A1 (n_337), .B0 (n_275), .Y
       (n_372));
  INVXL g3882(.A (n_344), .Y (n_345));
  NAND2X2 g3883__7482(.A (n_513), .B (n_336), .Y (n_346));
  AOI21X1 g3884__4733(.A0 (n_334), .A1 (n_330), .B0 (n_331), .Y
       (n_344));
  INVX2 g3885(.A (n_342), .Y (n_343));
  MXI2X1 g3886__6161(.A (n_440), .B (n_441), .S0 (n_320), .Y (n_369));
  AOI21XL g3887__9315(.A0 (n_148), .A1 (n_323), .B0 (n_314), .Y
       (n_341));
  OAI2BB1X2 g3888__9945(.A0N (n_315), .A1N (n_323), .B0 (n_337), .Y
       (n_342));
  NAND2BX1 g3889__2883(.AN (n_328), .B (n_513), .Y (n_338));
  NAND2BX1 g3890__2346(.AN (n_331), .B (n_334), .Y (n_340));
  NOR2BX1 g3892__1666(.AN (n_330), .B (n_332), .Y (n_339));
  OAI21X1 g3894__7410(.A0 (n_307), .A1 (n_312), .B0 (n_329), .Y
       (n_376));
  NAND2X1 g3895__6417(.A (n_145), .B (n_327), .Y (n_336));
  AOI21X2 g3896__5477(.A0 (n_315), .A1 (n_314), .B0 (n_316), .Y
       (n_337));
  NAND2X1 g3898__2398(.A (n_312), .B (n_307), .Y (n_329));
  NOR2BX1 g3899__5107(.AN (n_288), .B (n_626), .Y (n_335));
  NAND2XL g3900__6260(.A (n_291), .B (n_317), .Y (n_334));
  NAND2BX1 g3901__4319(.AN (n_288), .B (n_626), .Y (n_333));
  NOR2BX1 g3902__8428(.AN (n_292), .B (n_318), .Y (n_332));
  NOR2XL g3903__5526(.A (n_291), .B (n_317), .Y (n_331));
  NAND2BX1 g3904__6783(.AN (n_292), .B (n_318), .Y (n_330));
  INVXL g3905(.A (n_327), .Y (n_328));
  CLKXOR2X1 g3908__3680(.A (n_303), .B (n_144), .Y (n_368));
  NAND2X1 g3910__1617(.A (n_293), .B (n_305), .Y (n_327));
  NAND2BX1 g3911__2802(.AN (n_314), .B (n_148), .Y (n_320));
  NAND2X1 g3913__5122(.A (n_304), .B (n_502), .Y (n_323));
  AOI2BB1X1 g3914__8246(.A0N (n_307), .A1N (n_309), .B0 (n_178), .Y
       (n_322));
  AOI21X2 g3915__7098(.A0 (n_306), .A1 (n_310), .B0 (n_146), .Y
       (n_321));
  INVX1 g3916(.A (n_305), .Y (n_319));
  CLKINVX2 g3919(.A (n_313), .Y (n_314));
  ADDFXL g3920__6131(.A (n_190), .B (n_648), .CI (n_254), .CO (n_317),
       .S (n_318));
  NOR2X1 g3922__1881(.A (n_143), .B (n_301), .Y (n_316));
  NAND2X1 g3924__5115(.A (n_301), .B (n_143), .Y (n_315));
  NAND2X2 g3925__7482(.A (n_531), .B (n_297), .Y (n_313));
  XOR3X1 g3926__4733(.A (n_204), .B (n_173), .C (n_176), .Y (n_367));
  CLKXOR2X1 g3928__9315(.A (n_247), .B (n_296), .Y (n_375));
  NOR2BX1 g3930__9945(.AN (n_308), .B (n_178), .Y (n_312));
  INVXL g3932(.A (n_308), .Y (n_309));
  NAND2BX1 g3935__2883(.AN (n_251), .B (n_295), .Y (n_310));
  NAND2BX1 g3936__2346(.AN (n_239), .B (n_289), .Y (n_308));
  NOR2X1 g3938__1666(.A (n_247), .B (n_282), .Y (n_307));
  OAI21X1 g3939__7410(.A0 (n_223), .A1 (n_269), .B0 (n_622), .Y
       (n_306));
  OAI21X1 g3941__6417(.A0 (n_252), .A1 (n_177), .B0 (n_173), .Y
       (n_304));
  OAI21X1 g3943__5477(.A0 (n_646), .A1 (n_274), .B0 (n_273), .Y
       (n_305));
  NOR2BX1 g3944__2398(.AN (n_239), .B (n_289), .Y (n_178));
  NOR2XL g3946__5107(.A (n_173), .B (n_286), .Y (n_303));
  AOI21X1 g3950__4319(.A0 (n_266), .A1 (n_265), .B0 (n_264), .Y
       (n_301));
  INVX1 g3951(.A (n_299), .Y (n_300));
  NOR2XL g3955__8428(.A (n_241), .B (n_281), .Y (n_299));
  NOR2XL g3956__5526(.A (n_253), .B (n_283), .Y (n_298));
  AOI21X1 g3957__6783(.A0 (n_221), .A1 (n_139), .B0 (n_282), .Y
       (n_296));
  OAI21X2 g3958__3680(.A0 (n_141), .A1 (n_581), .B0 (n_625), .Y
       (n_297));
  OAI22X2 g3960__1617(.A0 (n_631), .A1 (n_138), .B0 (n_604), .B1
       (n_581), .Y (n_177));
  INVX1 g3961(.A (n_293), .Y (n_294));
  MXI2X1 g3962__2802(.A (n_592), .B (n_175), .S0 (n_255), .Y (n_295));
  MXI2X1 g3963__1705(.A (n_238), .B (n_140), .S0 (n_142), .Y (n_293));
  AOI2BB1X1 g3964__5122(.A0N (n_162), .A1N (n_601), .B0 (n_280), .Y
       (n_292));
  OAI21X1 g3965__8246(.A0 (n_268), .A1 (n_236), .B0 (n_285), .Y
       (n_291));
  MXI2X1 g3967__6131(.A (n_279), .B (n_259), .S0 (n_256), .Y (n_289));
  AOI21X1 g3968__1881(.A0 (n_175), .A1 (n_233), .B0 (n_246), .Y
       (n_288));
  NAND2XL g3970__5115(.A (n_236), .B (n_268), .Y (n_285));
  NOR2XL g3971__7482(.A (n_240), .B (n_267), .Y (n_284));
  NOR2X1 g3972__4733(.A (n_176), .B (n_204), .Y (n_286));
  AOI21XL g3973__6161(.A0 (n_162), .A1 (n_601), .B0 (n_279), .Y
       (n_280));
  AOI21XL g3974__9315(.A0 (n_444), .A1 (n_584), .B0 (n_236), .Y
       (n_283));
  NOR2XL g3975__9945(.A (n_221), .B (n_139), .Y (n_282));
  AOI21X1 g3976__2883(.A0 (n_584), .A1 (b_reg1[3]), .B0 (n_137), .Y
       (n_281));
  CLKINVX1 g3977(.A (n_259), .Y (n_279));
  INVXL g3978(.A (n_253), .Y (n_278));
  INVX1 g3979(.A (n_240), .Y (n_277));
  INVX1 g3983(.A (n_241), .Y (n_275));
  NOR2XL g3985__2346(.A (n_258), .B (n_534), .Y (n_274));
  NAND2XL g3986__1666(.A (n_258), .B (n_534), .Y (n_273));
  NAND2XL g3987__7410(.A (n_258), .B (n_535), .Y (n_271));
  NAND2XL g3988__6417(.A (n_539), .B (n_534), .Y (n_270));
  NOR2X1 g3990__2398(.A (n_621), .B (n_234), .Y (n_358));
  NAND2XL g3991__5107(.A (n_532), .B (n_174), .Y (n_265));
  AOI21X1 g3992__6260(.A0 (n_210), .A1 (n_192), .B0 (n_247), .Y
       (n_374));
  NOR2XL g3993__4319(.A (n_235), .B (n_173), .Y (n_366));
  NOR2XL g3994__8428(.A (n_532), .B (n_174), .Y (n_264));
  NOR2X1 g3995__5526(.A (n_136), .B (n_243), .Y (n_269));
  XNOR2XL g3996__6783(.A (n_225), .B (n_206), .Y (n_268));
  AOI21X1 g3997__3680(.A0 (n_444), .A1 (n_437), .B0 (n_238), .Y
       (n_267));
  OAI21X1 g3999__1617(.A0 (n_151), .A1 (n_199), .B0 (n_242), .Y
       (n_266));
  MXI2X1 g4004__2802(.A (n_168), .B (n_169), .S0 (n_170), .Y (n_176));
  AOI2BB2X1 g4005__1705(.A0N (n_171), .A1N (n_200), .B0 (n_200), .B1
       (n_518), .Y (n_263));
  MXI2X1 g4007__5122(.A (n_195), .B (n_600), .S0 (n_162), .Y (n_256));
  MXI2X1 g4008__8246(.A (n_552), .B (n_161), .S0 (n_212), .Y (n_255));
  MXI2X1 g4010__6131(.A (n_528), .B (n_529), .S0 (n_191), .Y (n_175));
  MXI2X1 g4012__1881(.A (n_543), .B (n_215), .S0 (n_205), .Y (n_259));
  CLKXOR2X1 g4013__5115(.A (n_649), .B (n_226), .Y (n_254));
  NAND2X1 g4014__7482(.A (n_232), .B (n_245), .Y (n_258));
  NOR2XL g4021__4733(.A (n_213), .B (n_551), .Y (n_246));
  NAND2BX1 g4023__6161(.AN (n_229), .B (n_202), .Y (n_245));
  NOR2XL g4025__9945(.A (n_198), .B (n_214), .Y (n_243));
  NAND2X1 g4026__2883(.A (n_151), .B (n_199), .Y (n_242));
  NOR2XL g4027__2346(.A (n_225), .B (n_206), .Y (n_253));
  NOR2XL g4028__1666(.A (n_170), .B (n_168), .Y (n_252));
  NOR2XL g4029__7410(.A (n_198), .B (n_167), .Y (n_251));
  NAND2X2 g4031__5477(.A (n_135), .B (n_151), .Y (n_174));
  NOR2XL g4032__2398(.A (n_208), .B (n_221), .Y (n_247));
  NOR2X1 g4033__5107(.A (n_204), .B (n_228), .Y (n_173));
  INVXL g4034(.A (n_140), .Y (n_238));
  AOI22XL g4036__6260(.A0 (a_reg1[5]), .A1 (b_reg1[0]), .B0
       (a_reg1[4]), .B1 (b_reg1[1]), .Y (n_235));
  AOI22X1 g4037__4319(.A0 (n_521), .A1 (a_reg1[1]), .B0 (n_554), .B1
       (n_634), .Y (n_234));
  NAND2XL g4038__8428(.A (n_213), .B (n_551), .Y (n_233));
  NAND2XL g4040__5526(.A (n_229), .B (n_418), .Y (n_232));
  NOR2XL g4042__3680(.A (n_518), .B (n_163), .Y (n_241));
  NOR2XL g4043__1617(.A (n_224), .B (n_422), .Y (n_240));
  NOR2XL g4044__2802(.A (n_201), .B (n_217), .Y (n_239));
  NOR2XL g4047__5122(.A (n_649), .B (n_226), .Y (n_236));
  CLKINVX1 g4050(.A (n_228), .Y (n_365));
  CLKINVX1 g4057(.A (n_222), .Y (n_223));
  CLKINVX1 g4064(.A (n_135), .Y (n_170));
  INVX1 g4067(.A (n_168), .Y (n_169));
  INVXL g4069(.A (n_214), .Y (n_167));
  INVXL g4070(.A (n_212), .Y (n_213));
  NAND2XL g4079__7098(.A (n_634), .B (a_reg1[4]), .Y (n_210));
  NAND2X1 g4080__6131(.A (b_reg1[6]), .B (a_reg1[2]), .Y (n_229));
  NAND2XL g4081__1881(.A (b_reg1[0]), .B (a_reg1[4]), .Y (n_228));
  NAND2XL g4083__7482(.A (n_423), .B (n_594), .Y (n_226));
  NAND2XL g4084__4733(.A (n_584), .B (n_423), .Y (n_225));
  NAND2X2 g4085__6161(.A (n_443), .B (n_497), .Y (n_224));
  NAND2XL g4086__9315(.A (a_reg1[6]), .B (b_reg1[3]), .Y (n_171));
  AND2X1 g4087__9945(.A (a_reg1[1]), .B (n_640), .Y (n_222));
  NAND2XL g4088__2883(.A (n_634), .B (a_reg1[5]), .Y (n_221));
  NAND2XL g4091__7410(.A (n_426), .B (a_reg1[4]), .Y (n_217));
  NAND2XL g4092__6417(.A (b_reg1[5]), .B (a_reg1[6]), .Y (n_215));
  NAND2XL g4094__5477(.A (a_reg1[4]), .B (b_reg1[2]), .Y (n_168));
  NOR2X2 g4095__2398(.A (n_524), .B (n_498), .Y (n_214));
  NOR2X2 g4096__5107(.A (n_561), .B (n_450), .Y (n_212));
  NAND2X2 g4098__4319(.A (a_reg1[1]), .B (n_443), .Y (n_164));
  CLKINVX1 g4101(.A (n_208), .Y (n_373));
  CLKINVX1 g4105(.A (n_163), .Y (n_200));
  NAND2XL g4116__8428(.A (n_521), .B (a_reg1[5]), .Y (n_192));
  NAND2X1 g4117__5526(.A (b_reg1[4]), .B (a_reg1[3]), .Y (n_191));
  NAND2XL g4118__6783(.A (a_reg1[7]), .B (b_reg1[0]), .Y (n_209));
  NAND2XL g4120__3680(.A (b_reg1[4]), .B (a_reg1[4]), .Y (n_208));
  NOR2X1 g4121__1617(.A (n_524), .B (n_559), .Y (n_357));
  NAND2XL g4123__1705(.A (n_444), .B (n_594), .Y (n_206));
  NAND2X1 g4124__5122(.A (b_reg1[4]), .B (a_reg1[7]), .Y (n_205));
  NAND2XL g4125__8246(.A (b_reg1[1]), .B (a_reg1[5]), .Y (n_204));
  NAND2X2 g4126__7098(.A (a_reg1[3]), .B (b_reg1[5]), .Y (n_202));
  NAND2XL g4127__6131(.A (b_reg1[4]), .B (n_594), .Y (n_201));
  NAND2X1 g4128__1881(.A (a_reg1[7]), .B (b_reg1[2]), .Y (n_163));
  NAND2X1 g4129__5115(.A (a_reg1[6]), .B (b_reg1[2]), .Y (n_199));
  NAND2X2 g4130__7482(.A (n_560), .B (n_426), .Y (n_198));
  AND2X1 g4132__4733(.A (n_444), .B (a_reg1[5]), .Y (n_190));
  NAND2X2 g4133__6161(.A (a_reg1[4]), .B (n_443), .Y (n_162));
  NAND2X2 g4135__9945(.A (a_reg1[5]), .B (n_426), .Y (n_195));
  NAND2X1 g4136__2883(.A (a_reg1[1]), .B (b_reg1[6]), .Y (n_161));
  INVXL g4137(.A (rst), .Y (n_1));
  XNOR2X1 g2__2346(.A (n_147), .B (n_306), .Y (n_360));
  CLKAND2X3 g4179__1666(.A (b_reg1[1]), .B (a_reg1[7]), .Y (n_151));
  CLKXOR2X1 g4181__7410(.A (n_321), .B (n_150), .Y (n_361));
  NAND2BX1 g4182__6417(.AN (n_335), .B (n_333), .Y (n_150));
  NOR2BXL g4183__5477(.AN (n_315), .B (n_316), .Y (n_149));
  OR2X1 g4184__2398(.A (n_297), .B (n_531), .Y (n_148));
  NAND2BXL g4185__5107(.AN (n_146), .B (n_310), .Y (n_147));
  NOR2BX1 g4186__6260(.AN (n_251), .B (n_295), .Y (n_146));
  AO21XL g4187__4319(.A0 (n_271), .A1 (n_270), .B0 (n_288), .Y (n_145));
  XNOR2XL g4188__8428(.A (n_177), .B (n_252), .Y (n_144));
  CLKXOR2X1 g4189__5526(.A (n_137), .B (n_263), .Y (n_143));
  MXI2X1 g4190__6783(.A (n_422), .B (n_645), .S0 (n_224), .Y (n_142));
  NOR2BXL g4191__3680(.AN (n_605), .B (n_644), .Y (n_141));
  NAND2BXL g4192__1617(.AN (n_529), .B (n_645), .Y (n_140));
  XNOR2X1 g4193__2802(.A (n_217), .B (n_201), .Y (n_139));
  XNOR2X1 g4194__1705(.A (n_209), .B (n_134), .Y (n_138));
  NOR2BXL g4195__5122(.AN (n_151), .B (n_199), .Y (n_137));
  NOR2BX1 g4196__8246(.AN (n_198), .B (n_167), .Y (n_136));
  CLKAND2X2 g4198__7098(.A (b_reg1[0]), .B (a_reg1[6]), .Y (n_135));
  NOR2BX1 g4199__6131(.AN (a_reg1[6]), .B (n_566), .Y (n_134));
  ADDFHXL g4201__1881(.A (n_223), .B (n_621), .CI (n_460), .CO
       (UNCONNECTED), .S (n_359));
  DFFRHQX1 \a_reg1_reg[0] (.RN (n_1), .CK (clk), .D (n_38), .Q
       (a_reg1[0]));
  DFFRHQX4 \a_reg1_reg[1] (.RN (n_1), .CK (clk), .D (n_36), .Q
       (a_reg1[1]));
  DFFRHQX4 \a_reg1_reg[2] (.RN (n_1), .CK (clk), .D (n_37), .Q
       (a_reg1[2]));
  DFFRHQX4 \a_reg1_reg[3] (.RN (n_1), .CK (clk), .D (n_35), .Q
       (a_reg1[3]));
  SDFFRHQX4 \a_reg1_reg[4] (.RN (n_1), .CK (clk), .D (a_reg1[4]), .SI
       (a[4]), .SE (valid_i), .Q (a_reg1[4]));
  SDFFRHQX4 \a_reg1_reg[5] (.RN (n_1), .CK (clk), .D (a_reg1[5]), .SI
       (a[5]), .SE (valid_i), .Q (a_reg1[5]));
  SDFFRHQX4 \a_reg1_reg[6] (.RN (n_1), .CK (clk), .D (n_594), .SI
       (a[6]), .SE (valid_i), .Q (a_reg1[6]));
  SDFFRHQX4 \a_reg1_reg[7] (.RN (n_1), .CK (clk), .D (n_584), .SI
       (a[7]), .SE (valid_i), .Q (a_reg1[7]));
  DFFRHQX4 \b_reg1_reg[0] (.RN (n_1), .CK (clk), .D (n_34), .Q
       (b_reg1[0]));
  DFFRHQX4 \b_reg1_reg[1] (.RN (n_1), .CK (clk), .D (n_39), .Q
       (b_reg1[1]));
  DFFRHQX4 \b_reg1_reg[2] (.RN (n_1), .CK (clk), .D (n_33), .Q
       (b_reg1[2]));
  DFFRHQX4 \b_reg1_reg[3] (.RN (n_1), .CK (clk), .D (n_32), .Q
       (b_reg1[3]));
  SDFFRHQX4 \b_reg1_reg[4] (.RN (n_1), .CK (clk), .D (n_521), .SI
       (b[4]), .SE (valid_i), .Q (b_reg1[4]));
  SDFFRHQX4 \b_reg1_reg[5] (.RN (n_1), .CK (clk), .D (n_634), .SI
       (b[5]), .SE (valid_i), .Q (b_reg1[5]));
  SDFFRHQX4 \b_reg1_reg[6] (.RN (n_1), .CK (clk), .D (n_423), .SI
       (b[6]), .SE (valid_i), .Q (b_reg1[6]));
  SDFFRHQX1 \b_reg1_reg[7] (.RN (n_1), .CK (clk), .D (n_444), .SI
       (b[7]), .SE (valid_i), .Q (b_reg1[7]));
  SDFFRHQX1 \partial1_reg[0] (.RN (n_1), .CK (clk), .D (n_28), .SI
       (partial1[0]), .SE (n_4), .Q (partial1[0]));
  SDFFRHQX1 \partial1_reg[2] (.RN (n_1), .CK (clk), .D (partial1[2]),
       .SI (n_70), .SE (valid_stage1), .Q (partial1[2]));
  SDFFRHQX1 \partial1_reg[3] (.RN (n_1), .CK (clk), .D (partial1[3]),
       .SI (n_87), .SE (valid_stage1), .Q (partial1[3]));
  SDFFRHQX1 \partial1_reg[4] (.RN (n_1), .CK (clk), .D (partial1[4]),
       .SI (n_90), .SE (valid_stage1), .Q (partial1[4]));
  SDFFRHQX1 \partial1_reg[6] (.RN (n_1), .CK (clk), .D (partial1[6]),
       .SI (n_96), .SE (valid_stage1), .Q (partial1[6]));
  SDFFRHQX1 \partial2_reg[4] (.RN (n_1), .CK (clk), .D (partial2[4]),
       .SI (n_393), .SE (valid_stage1), .Q (partial2[4]));
  SDFFRHQX1 \partial2_reg[5] (.RN (n_1), .CK (clk), .D (partial2[5]),
       .SI (n_392), .SE (valid_stage1), .Q (partial2[5]));
  SDFFRHQX1 \partial2_reg[6] (.RN (n_1), .CK (clk), .D (partial2[6]),
       .SI (n_391), .SE (valid_stage1), .Q (partial2[6]));
  SDFFRXL \partial2_reg[13] (.RN (n_1), .CK (clk), .D (n_384), .SI
       (partial2[13]), .SE (n_4), .Q (partial2[13]), .QN
       (UNCONNECTED0));
  SDFFRXL \partial2_reg[14] (.RN (n_1), .CK (clk), .D (n_383), .SI
       (partial2[14]), .SE (n_4), .Q (partial2[14]), .QN
       (UNCONNECTED1));
  SDFFRXL \partial2_reg[15] (.RN (n_1), .CK (clk), .D (n_382), .SI
       (partial2[15]), .SE (n_4), .Q (partial2[15]), .QN
       (UNCONNECTED2));
  SDFFRHQX1 \product_reg[0] (.RN (n_1), .CK (clk), .D (n_118), .SI
       (partial1[0]), .SE (valid_stage2), .Q (n_118));
  SDFFRHQX1 \product_reg[1] (.RN (n_1), .CK (clk), .D (n_119), .SI
       (partial1[1]), .SE (valid_stage2), .Q (n_119));
  SDFFRHQX1 \product_reg[2] (.RN (n_1), .CK (clk), .D (n_120), .SI
       (partial1[2]), .SE (valid_stage2), .Q (n_120));
  SDFFRHQX1 \product_reg[3] (.RN (n_1), .CK (clk), .D (n_121), .SI
       (partial1[3]), .SE (valid_stage2), .Q (n_121));
  DFFRHQX1 \product_reg[4] (.RN (n_1), .CK (clk), .D (n_54), .Q
       (n_122));
  SDFFRHQX1 \product_reg[5] (.RN (n_1), .CK (clk), .D (n_55), .SI
       (n_123), .SE (n_2), .Q (n_123));
  SDFFRHQX1 \product_reg[6] (.RN (n_1), .CK (clk), .D (n_67), .SI
       (n_124), .SE (n_2), .Q (n_124));
  SDFFRHQX1 \product_reg[7] (.RN (n_1), .CK (clk), .D (n_79), .SI
       (n_125), .SE (n_2), .Q (n_125));
  DFFRHQX1 \product_reg[8] (.RN (n_1), .CK (clk), .D (n_101), .Q
       (n_126));
  SDFFRHQX1 \product_reg[9] (.RN (n_1), .CK (clk), .D (n_100), .SI
       (n_127), .SE (n_2), .Q (n_127));
  DFFRHQX1 \product_reg[10] (.RN (n_1), .CK (clk), .D (n_106), .Q
       (n_128));
  SDFFRHQX1 \product_reg[11] (.RN (n_1), .CK (clk), .D (n_105), .SI
       (n_129), .SE (n_2), .Q (n_129));
  DFFRHQX1 \product_reg[12] (.RN (n_1), .CK (clk), .D (n_111), .Q
       (n_130));
  SDFFRHQX1 \product_reg[13] (.RN (n_1), .CK (clk), .D (n_110), .SI
       (n_131), .SE (n_2), .Q (n_131));
  DFFRHQX1 \product_reg[14] (.RN (n_1), .CK (clk), .D (n_116), .Q
       (n_132));
  SDFFRHQX1 \product_reg[15] (.RN (n_1), .CK (clk), .D (n_133), .SI
       (n_115), .SE (valid_stage2), .Q (n_133));
  DFFRHQX1 valid_o_reg(.RN (n_1), .CK (clk), .D (valid_stage2), .Q
       (n_117));
  OAI2BB1XL g3367__5115(.A0N (n_132), .A1N (n_2), .B0 (n_113), .Y
       (n_116));
  OAI21X1 g3368__7482(.A0 (partial2[15]), .A1 (n_112), .B0 (n_114), .Y
       (n_115));
  NAND2XL g3369__4733(.A (partial2[15]), .B (n_112), .Y (n_114));
  OAI211XL g3370__6161(.A0 (n_109), .A1 (partial2[14]), .B0
       (valid_stage2), .C0 (n_112), .Y (n_113));
  NAND2X1 g3372__9315(.A (n_109), .B (partial2[14]), .Y (n_112));
  OAI2BB1XL g3374__9945(.A0N (n_130), .A1N (n_2), .B0 (n_108), .Y
       (n_111));
  AOI21X1 g3375__2883(.A0 (n_5), .A1 (n_107), .B0 (n_109), .Y (n_110));
  NOR2X1 g3376__2346(.A (n_5), .B (n_107), .Y (n_109));
  OAI211XL g3377__1666(.A0 (n_104), .A1 (partial2[12]), .B0
       (valid_stage2), .C0 (n_107), .Y (n_108));
  NAND2X1 g3379__7410(.A (partial2[12]), .B (n_104), .Y (n_107));
  OAI2BB1XL g3381__6417(.A0N (n_128), .A1N (n_2), .B0 (n_103), .Y
       (n_106));
  AOI21X1 g3382__5477(.A0 (n_6), .A1 (n_102), .B0 (n_104), .Y (n_105));
  NOR2X2 g3383__2398(.A (n_6), .B (n_102), .Y (n_104));
  OAI211XL g3384__5107(.A0 (n_99), .A1 (partial2[10]), .B0
       (valid_stage2), .C0 (n_102), .Y (n_103));
  NAND2X2 g3388__6260(.A (partial2[10]), .B (n_99), .Y (n_102));
  OAI2BB1XL g3392__4319(.A0N (n_126), .A1N (n_2), .B0 (n_98), .Y
       (n_101));
  AOI21X1 g3393__8428(.A0 (n_3), .A1 (n_89), .B0 (n_99), .Y (n_100));
  OAI211X1 g3394__5526(.A0 (partial2[8]), .A1 (n_80), .B0
       (valid_stage2), .C0 (n_89), .Y (n_98));
  NOR2X2 g3395__6783(.A (n_3), .B (n_89), .Y (n_99));
  OAI21X1 g3397__1617(.A0 (n_63), .A1 (n_93), .B0 (n_95), .Y (n_96));
  NAND2XL g3400__2802(.A (n_93), .B (n_63), .Y (n_95));
  OAI21X1 g3402__5122(.A0 (n_59), .A1 (n_84), .B0 (n_53), .Y (n_92));
  AOI2BB1X1 g3403__8246(.A0N (n_74), .A1N (n_86), .B0 (n_83), .Y
       (n_93));
  OAI21X1 g3404__7098(.A0 (n_86), .A1 (n_81), .B0 (n_88), .Y (n_90));
  OAI21X1 g3405__6131(.A0 (n_76), .A1 (n_86), .B0 (n_78), .Y (n_91));
  NAND2X2 g3406__1881(.A (partial2[8]), .B (n_80), .Y (n_89));
  NAND2XL g3407__5115(.A (n_86), .B (n_81), .Y (n_88));
  INVX1 g3408(.A (n_85), .Y (n_87));
  ADDFHX2 g3409__7482(.A (n_69), .B (n_41), .CI (n_65), .CO (n_86), .S
       (n_85));
  INVXL g3411(.A (n_83), .Y (n_84));
  AOI21X1 g3413__4733(.A0 (n_75), .A1 (n_78), .B0 (n_74), .Y (n_83));
  NAND2BX1 g3414__6161(.AN (n_74), .B (n_75), .Y (n_82));
  NOR2BX1 g3415__9315(.AN (n_78), .B (n_76), .Y (n_81));
  OAI21X1 g3416__9945(.A0 (n_47), .A1 (n_73), .B0 (n_77), .Y (n_79));
  AOI21X2 g3417__2883(.A0 (n_29), .A1 (n_68), .B0 (n_30), .Y (n_80));
  NAND2XL g3418__2346(.A (n_47), .B (n_73), .Y (n_77));
  NAND2BX1 g3419__1666(.AN (n_66), .B (n_72), .Y (n_78));
  NOR2BXL g3420__7410(.AN (n_66), .B (n_72), .Y (n_76));
  NAND2XL g3421__6417(.A (n_62), .B (n_71), .Y (n_75));
  NOR2XL g3422__5477(.A (n_62), .B (n_71), .Y (n_74));
  CLKINVX1 g3423(.A (n_68), .Y (n_73));
  ADDFX1 g3424__2398(.A (n_8), .B (n_40), .CI (n_0), .CO (n_71), .S
       (n_72));
  CLKXOR2X1 g3426__5107(.A (n_42), .B (n_61), .Y (n_70));
  NOR2X1 g3427__6260(.A (n_60), .B (n_42), .Y (n_69));
  OAI21X1 g3428__4319(.A0 (n_45), .A1 (n_57), .B0 (n_64), .Y (n_67));
  OAI21X1 g3429__8428(.A0 (n_19), .A1 (n_57), .B0 (n_17), .Y (n_68));
  ADDFHXL g3430__5526(.A (n_21), .B (n_9), .CI (n_48), .CO (n_66), .S
       (n_65));
  NAND2XL g3431__6783(.A (n_45), .B (n_57), .Y (n_64));
  NOR2XL g3434__3680(.A (n_44), .B (n_59), .Y (n_63));
  AOI21XL g3435__1617(.A0 (n_22), .A1 (n_49), .B0 (n_60), .Y (n_61));
  OAI21X1 g3436__2802(.A0 (n_43), .A1 (n_50), .B0 (n_58), .Y (n_62));
  NAND2XL g3437__1705(.A (n_43), .B (n_50), .Y (n_58));
  NOR2XL g3438__5122(.A (n_49), .B (n_22), .Y (n_60));
  AOI21X1 g3439__8246(.A0 (n_433), .A1 (b_reg1[3]), .B0 (n_43), .Y
       (n_59));
  OAI32X1 g3440__7098(.A0 (n_4), .A1 (n_31), .A2 (n_42), .B0
       (valid_stage1), .B1 (n_7), .Y (n_56));
  OAI21X1 g3441__6131(.A0 (n_10), .A1 (n_46), .B0 (n_52), .Y (n_55));
  OAI2BB1XL g3442__1881(.A0N (n_122), .A1N (n_2), .B0 (n_51), .Y
       (n_54));
  AOI21X1 g3443__5115(.A0 (n_26), .A1 (n_10), .B0 (n_20), .Y (n_57));
  INVXL g3444(.A (n_44), .Y (n_53));
  NAND2XL g3446__7482(.A (n_10), .B (n_46), .Y (n_52));
  OAI211X1 g3447__4733(.A0 (partial1[4]), .A1 (partial2[4]), .B0
       (n_10), .C0 (valid_stage2), .Y (n_51));
  XNOR2XL g3472__6161(.A (n_13), .B (n_11), .Y (n_50));
  MXI2XL g3473__9315(.A (n_14), .B (n_15), .S0 (n_23), .Y (n_49));
  XNOR2X1 g3478__9945(.A (n_25), .B (n_12), .Y (n_48));
  NAND2BX1 g3484__2883(.AN (n_30), .B (n_29), .Y (n_47));
  NAND2BX1 g3485__2346(.AN (n_23), .B (n_15), .Y (n_41));
  NOR2BX1 g3486__1666(.AN (n_26), .B (n_20), .Y (n_46));
  NAND2XL g3487__7410(.A (n_18), .B (n_17), .Y (n_45));
  NOR2XL g3488__6417(.A (n_11), .B (n_13), .Y (n_44));
  NOR2XL g3489__5477(.A (n_16), .B (n_24), .Y (n_43));
  NOR2XL g3490__2398(.A (n_27), .B (n_22), .Y (n_42));
  NOR2XL g3491__5107(.A (n_25), .B (n_12), .Y (n_40));
  MX2X1 g3492__6260(.A (n_562), .B (b[1]), .S0 (valid_i), .Y (n_39));
  MX2X1 g3493__4319(.A (n_554), .B (a[0]), .S0 (valid_i), .Y (n_38));
  MX2X1 g3494__8428(.A (n_493), .B (a[2]), .S0 (valid_i), .Y (n_37));
  MX2X1 g3495__5526(.A (n_471), .B (a[1]), .S0 (valid_i), .Y (n_36));
  MX2X1 g3496__6783(.A (n_433), .B (a[3]), .S0 (valid_i), .Y (n_35));
  MX2X1 g3497__3680(.A (b_reg1[0]), .B (b[0]), .S0 (valid_i), .Y
       (n_34));
  MX2X1 g3498__1617(.A (b_reg1[2]), .B (b[2]), .S0 (valid_i), .Y
       (n_33));
  MX2X1 g3499__2802(.A (b_reg1[3]), .B (b[3]), .S0 (valid_i), .Y
       (n_32));
  AOI22XL g3500__1705(.A0 (n_554), .A1 (n_562), .B0 (n_471), .B1
       (b_reg1[0]), .Y (n_31));
  INVXL g3501(.A (n_27), .Y (n_28));
  NOR2XL g3504__5122(.A (partial1[7]), .B (partial2[7]), .Y (n_30));
  NAND2XL g3505__8246(.A (partial1[7]), .B (partial2[7]), .Y (n_29));
  NAND2XL g3506__7098(.A (n_554), .B (b_reg1[0]), .Y (n_27));
  NAND2XL g3507__6131(.A (partial1[5]), .B (partial2[5]), .Y (n_26));
  NAND2XL g3508__1881(.A (n_433), .B (b_reg1[0]), .Y (n_25));
  NAND2XL g3509__5115(.A (n_433), .B (n_562), .Y (n_24));
  NAND2XL g3510__7482(.A (n_554), .B (b_reg1[2]), .Y (n_23));
  NAND2XL g3511__4733(.A (n_471), .B (n_562), .Y (n_22));
  NAND2XL g3512__6161(.A (n_471), .B (b_reg1[2]), .Y (n_21));
  INVX1 g3514(.A (n_18), .Y (n_19));
  CLKINVX1 g3515(.A (n_14), .Y (n_15));
  NOR2XL g3516__9315(.A (partial1[5]), .B (partial2[5]), .Y (n_20));
  NAND2XL g3517__9945(.A (partial1[6]), .B (partial2[6]), .Y (n_18));
  OR2X1 g3518__2883(.A (partial1[6]), .B (partial2[6]), .Y (n_17));
  NAND2XL g3519__2346(.A (n_494), .B (b_reg1[2]), .Y (n_16));
  NAND2XL g3520__1666(.A (n_494), .B (b_reg1[0]), .Y (n_14));
  NAND2XL g3521__7410(.A (n_433), .B (b_reg1[2]), .Y (n_13));
  NAND2X1 g3522__6417(.A (n_494), .B (n_562), .Y (n_12));
  NAND2XL g3523__5477(.A (n_493), .B (b_reg1[3]), .Y (n_11));
  NAND2XL g3524__2398(.A (n_554), .B (b_reg1[3]), .Y (n_9));
  AND2X1 g3525__5107(.A (b_reg1[3]), .B (n_471), .Y (n_8));
  NAND2X2 g3526__6260(.A (partial1[4]), .B (partial2[4]), .Y (n_10));
  BUFX2 g3527(.A (n_127), .Y (product[9]));
  BUFX2 g3528(.A (n_121), .Y (product[3]));
  BUFX2 g3530(.A (n_119), .Y (product[1]));
  BUFX2 g3531(.A (n_124), .Y (product[6]));
  BUFX2 g3532(.A (n_133), .Y (product[15]));
  BUFX2 g3533(.A (n_120), .Y (product[2]));
  CLKINVX1 g3534(.A (partial2[11]), .Y (n_6));
  INVX1 g3535(.A (partial2[13]), .Y (n_5));
  BUFX2 g3537(.A (n_131), .Y (product[13]));
  BUFX2 g3538(.A (n_123), .Y (product[5]));
  BUFX2 g3539(.A (n_118), .Y (product[0]));
  BUFX2 g3540(.A (n_125), .Y (product[7]));
  BUFX2 g3541(.A (n_129), .Y (product[11]));
  CLKINVX1 g3542(.A (partial2[9]), .Y (n_3));
  BUFX2 drc_bufs3547(.A (n_132), .Y (product[14]));
  BUFX2 drc_bufs3550(.A (n_130), .Y (product[12]));
  BUFX2 drc_bufs3553(.A (n_122), .Y (product[4]));
  BUFX2 drc_bufs3556(.A (n_126), .Y (product[8]));
  BUFX2 drc_bufs3559(.A (n_128), .Y (product[10]));
  BUFX2 drc_bufs(.A (n_117), .Y (valid_o));
  CLKXOR2X1 g4202__4319(.A (n_24), .B (n_16), .Y (n_0));
  MXI2XL WALLACE_CSA_DUMMY_OP_groupi_g956__8428(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_79), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_80), .S0 (n_380), .Y (n_382));
  MXI2XL WALLACE_CSA_DUMMY_OP_groupi_g957__5526(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_82), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_83), .S0 (n_627), .Y (n_383));
  MXI2X1 WALLACE_CSA_DUMMY_OP_groupi_g958__6783(.A (n_642), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_84), .S0 (n_378), .Y (n_384));
  MXI2X1 WALLACE_CSA_DUMMY_OP_groupi_g959__3680(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_77), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_76), .S0
       (WALLACE_CSA_DUMMY_OP_groupi_n_53), .Y (n_386));
  OAI2BB1X1 WALLACE_CSA_DUMMY_OP_groupi_g961__1617(.A0N
       (WALLACE_CSA_DUMMY_OP_groupi_n_51), .A1N
       (WALLACE_CSA_DUMMY_OP_groupi_n_72), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_52), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_84));
  INVXL WALLACE_CSA_DUMMY_OP_groupi_g962(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_82), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_83));
  AOI21XL WALLACE_CSA_DUMMY_OP_groupi_g963__2802(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_57), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_72), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_56), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_82));
  OAI21XL WALLACE_CSA_DUMMY_OP_groupi_g964__1705(.A0 (n_509), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_54), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_78), .Y (n_385));
  INVXL WALLACE_CSA_DUMMY_OP_groupi_g965(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_79), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_80));
  AOI31X1 WALLACE_CSA_DUMMY_OP_groupi_g966__5122(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_72), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_57), .A2 (n_627), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_60), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_79));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g967__8246(.A (n_509), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_54), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_78));
  INVX1 WALLACE_CSA_DUMMY_OP_groupi_g968(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_76), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_77));
  OAI21X2 WALLACE_CSA_DUMMY_OP_groupi_g969__7098(.A0 (n_547), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_70), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_40), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_76));
  MXI2X1 WALLACE_CSA_DUMMY_OP_groupi_g970__6131(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_69), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_70), .S0
       (WALLACE_CSA_DUMMY_OP_groupi_n_47), .Y (n_387));
  OAI21XL WALLACE_CSA_DUMMY_OP_groupi_g971__1881(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_68), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_46), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_73), .Y (n_388));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g972__5115(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_46), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_68), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_73));
  NAND3X2 WALLACE_CSA_DUMMY_OP_groupi_g973__7482(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_58), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_59), .C
       (WALLACE_CSA_DUMMY_OP_groupi_n_71), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_72));
  NAND2X2 WALLACE_CSA_DUMMY_OP_groupi_g974__4733(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_5), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_55), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_71));
  CLKINVX1 WALLACE_CSA_DUMMY_OP_groupi_g975(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_70), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_69));
  NOR2BX2 WALLACE_CSA_DUMMY_OP_groupi_g976__6161(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_39), .B (n_451), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_70));
  AOI21XL WALLACE_CSA_DUMMY_OP_groupi_g977__9315(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_30), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_65), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_29), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_68));
  OAI21XL WALLACE_CSA_DUMMY_OP_groupi_g978__9945(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_34), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_65), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_66), .Y (n_389));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g979__2883(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_65), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_34), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_66));
  NOR3BX2 WALLACE_CSA_DUMMY_OP_groupi_g981__2346(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_30), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_64), .C
       (WALLACE_CSA_DUMMY_OP_groupi_n_41), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_5));
  INVX1 WALLACE_CSA_DUMMY_OP_groupi_g982(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_65), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_64));
  ADDFHXL WALLACE_CSA_DUMMY_OP_groupi_g983__1666(.A (n_368), .B
       (n_360), .CI (WALLACE_CSA_DUMMY_OP_groupi_n_61), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_65), .S (n_390));
  ADDFHX2 WALLACE_CSA_DUMMY_OP_groupi_g984__7410(.A (n_367), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_33), .CI (n_359), .CO
       (WALLACE_CSA_DUMMY_OP_groupi_n_61), .S (n_391));
  AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g985__6417(.A (n_627), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_56), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_60));
  NAND3X2 WALLACE_CSA_DUMMY_OP_groupi_g986__5477(.A (n_549), .B
       (n_508), .C (WALLACE_CSA_DUMMY_OP_groupi_n_38), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_59));
  AOI21X2 WALLACE_CSA_DUMMY_OP_groupi_g987__2398(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_1), .A1 (n_508), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_50), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_58));
  AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g988__5107(.A (n_378), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_51), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_57));
  NOR2BX1 WALLACE_CSA_DUMMY_OP_groupi_g989__6260(.AN (n_378), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_52), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_56));
  NOR2X1 WALLACE_CSA_DUMMY_OP_groupi_g990__4319(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_42), .B (n_480), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_55));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g991__8428(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_52), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_51), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_54));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g992__5526(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_50), .B (n_480), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_53));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g993__6783(.A (n_377), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_44), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_52));
  OR2X1 WALLACE_CSA_DUMMY_OP_groupi_g994__3680(.A (n_377), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_44), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_51));
  NOR2BX1 WALLACE_CSA_DUMMY_OP_groupi_g995__1617(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_45), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_25), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_50));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g998__1705(.A (n_548), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_40), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_47));
  MXI2X1 WALLACE_CSA_DUMMY_OP_groupi_g999__5122(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_37), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_36), .S0
       (WALLACE_CSA_DUMMY_OP_groupi_n_14), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_46));
  ADDFHXL WALLACE_CSA_DUMMY_OP_groupi_g1000__8246(.A (n_372), .B
       (n_364), .CI (n_376), .CO (WALLACE_CSA_DUMMY_OP_groupi_n_44), .S
       (WALLACE_CSA_DUMMY_OP_groupi_n_45));
  NOR2X1 WALLACE_CSA_DUMMY_OP_groupi_g1004__7098(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_27), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_26), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_42));
  NOR2BX1 WALLACE_CSA_DUMMY_OP_groupi_g1005__6131(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_14), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_28), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_41));
  INVXL WALLACE_CSA_DUMMY_OP_groupi_g1006(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_1), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_40));
  INVXL WALLACE_CSA_DUMMY_OP_groupi_g1008(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_38), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_39));
  NOR2X2 WALLACE_CSA_DUMMY_OP_groupi_g1009__1881(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_0), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_35), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_38));
  CLKINVX1 WALLACE_CSA_DUMMY_OP_groupi_g1011(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_36), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_37));
  CLKBUFX2 WALLACE_CSA_DUMMY_OP_groupi_g1012(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_35), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_36));
  INVX1 WALLACE_CSA_DUMMY_OP_groupi_g1013(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_28), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_35));
  NAND2BX1 WALLACE_CSA_DUMMY_OP_groupi_g1016__5115(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_29), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_30), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_34));
  OAI21X1 WALLACE_CSA_DUMMY_OP_groupi_g1017__7482(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_15), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_12), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_9), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_33));
  OAI21X1 WALLACE_CSA_DUMMY_OP_groupi_g1018__4733(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_15), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_24), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_31), .Y (n_392));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g1019__6161(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_15), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_24), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_31));
  NAND2BX1 WALLACE_CSA_DUMMY_OP_groupi_g1020__9315(.AN (n_361), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_23), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_30));
  NOR2BX2 WALLACE_CSA_DUMMY_OP_groupi_g1021__9945(.AN (n_361), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_23), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_29));
  MXI2X1 WALLACE_CSA_DUMMY_OP_groupi_g1022__2883(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_20), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_19), .S0 (n_370), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_28));
  MXI2X1 WALLACE_CSA_DUMMY_OP_groupi_g1023__2346(.A (n_608), .B
       (n_612), .S0 (n_371), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_27));
  OAI21X1 WALLACE_CSA_DUMMY_OP_groupi_g1025__1666(.A0
       (WALLACE_CSA_DUMMY_OP_groupi_n_3), .A1
       (WALLACE_CSA_DUMMY_OP_groupi_n_10), .B0
       (WALLACE_CSA_DUMMY_OP_groupi_n_16), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_26));
  CLKAND2X2 WALLACE_CSA_DUMMY_OP_groupi_g1026__7410(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_11), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_21), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_25));
  NOR2BXL WALLACE_CSA_DUMMY_OP_groupi_g1027__6417(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_9), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_12), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_24));
  NAND2X2 WALLACE_CSA_DUMMY_OP_groupi_g1028__5477(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_14), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_13), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_23));
  OA21X1 WALLACE_CSA_DUMMY_OP_groupi_g1029__2398(.A0 (n_357), .A1
       (n_365), .B0 (WALLACE_CSA_DUMMY_OP_groupi_n_15), .Y (n_393));
  OAI21X1 WALLACE_CSA_DUMMY_OP_groupi_g1030__5107(.A0 (n_375), .A1
       (n_371), .B0 (WALLACE_CSA_DUMMY_OP_groupi_n_8), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_21));
  INVX1 WALLACE_CSA_DUMMY_OP_groupi_g1031(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_19), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_20));
  MXI2X1 WALLACE_CSA_DUMMY_OP_groupi_g1032__6260(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_2), .B (n_362), .S0 (n_374), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_19));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g1035__8428(.A (n_374), .B
       (n_370), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_16));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g1036__5526(.A (n_357), .B
       (n_365), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_15));
  NAND2X2 WALLACE_CSA_DUMMY_OP_groupi_g1037__6783(.A (n_373), .B
       (n_369), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_14));
  OR2X1 WALLACE_CSA_DUMMY_OP_groupi_g1038__3680(.A (n_373), .B (n_369),
       .Y (WALLACE_CSA_DUMMY_OP_groupi_n_13));
  NOR2X1 WALLACE_CSA_DUMMY_OP_groupi_g1039__1617(.A (n_366), .B
       (n_358), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_12));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g1040__2802(.A (n_371), .B
       (n_375), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_11));
  NOR2XL WALLACE_CSA_DUMMY_OP_groupi_g1041__1705(.A (n_374), .B
       (n_370), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_10));
  NAND2XL WALLACE_CSA_DUMMY_OP_groupi_g1042__5122(.A (n_366), .B
       (n_358), .Y (WALLACE_CSA_DUMMY_OP_groupi_n_9));
  INVXL WALLACE_CSA_DUMMY_OP_groupi_fopt(.A (n_362), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_3));
  INVX1 WALLACE_CSA_DUMMY_OP_groupi_fopt1047(.A (n_362), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_2));
  AND2X1 WALLACE_CSA_DUMMY_OP_groupi_g2__8246(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_26), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_27), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_1));
  NOR2BX1 WALLACE_CSA_DUMMY_OP_groupi_g1051__7098(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_14), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_29), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_0));
  INVX1 fopt(.A (n_202), .Y (n_418));
  CLKINVX1 fopt4203(.A (n_645), .Y (n_422));
  BUFX3 fopt2(.A (n_426), .Y (n_423));
  CLKINVX2 fopt3(.A (n_428), .Y (n_426));
  INVX1 fopt5(.A (b_reg1[6]), .Y (n_428));
  CLKINVX1 fopt4211(.A (n_438), .Y (n_433));
  INVX1 fopt4212(.A (n_438), .Y (n_437));
  INVXL fopt4213(.A (a_reg1[3]), .Y (n_438));
  INVX1 fopt4214(.A (n_441), .Y (n_440));
  INVX1 fopt4215(.A (n_323), .Y (n_441));
  INVX1 fopt4219(.A (n_448), .Y (n_444));
  INVXL fopt4221(.A (n_443), .Y (n_448));
  INVX3 fopt6(.A (n_450), .Y (n_443));
  CLKINVX2 fopt7(.A (b_reg1[7]), .Y (n_450));
  BUFX2 fopt4222(.A (WALLACE_CSA_DUMMY_OP_groupi_n_5), .Y (n_451));
  BUFX3 fopt4229(.A (n_269), .Y (n_460));
  INVX1 fopt4240(.A (n_475), .Y (n_471));
  CLKINVX1 fopt4245(.A (a_reg1[1]), .Y (n_475));
  INVX2 fopt4247(.A (n_507), .Y (n_480));
  CLKBUFX2 fopt4253(.A (n_494), .Y (n_493));
  CLKBUFX2 fopt4256(.A (n_497), .Y (n_494));
  CLKINVX2 fopt4257(.A (n_498), .Y (n_497));
  CLKINVX2 fopt4258(.A (a_reg1[2]), .Y (n_498));
  SDFFRXL \partial2_reg[12] (.RN (n_1), .CK (clk), .D (partial2[12]),
       .SI (n_385), .SE (valid_stage1), .Q (partial2[12]), .QN
       (UNCONNECTED3));
  SDFFRXL \partial2_reg[10] (.RN (n_1), .CK (clk), .D (partial2[10]),
       .SI (n_387), .SE (valid_stage1), .Q (partial2[10]), .QN
       (UNCONNECTED4));
  SDFFRXL \partial2_reg[11] (.RN (n_1), .CK (clk), .D (partial2[11]),
       .SI (n_386), .SE (valid_stage1), .Q (partial2[11]), .QN
       (UNCONNECTED5));
  SDFFRXL \partial2_reg[8] (.RN (n_1), .CK (clk), .D (partial2[8]), .SI
       (n_389), .SE (valid_stage1), .Q (partial2[8]), .QN
       (UNCONNECTED6));
  SDFFRXL \partial2_reg[9] (.RN (n_1), .CK (clk), .D (partial2[9]), .SI
       (n_388), .SE (valid_stage1), .Q (partial2[9]), .QN
       (UNCONNECTED7));
  OAI21X1 g2(.A0 (n_286), .A1 (n_252), .B0 (n_177), .Y (n_502));
  NAND2BX2 WALLACE_CSA_DUMMY_OP_groupi_g997__4280(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_45), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_25), .Y (n_507));
  NAND2BX2 WALLACE_CSA_DUMMY_OP_groupi_g997__2802_1(.AN
       (WALLACE_CSA_DUMMY_OP_groupi_n_45), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_25), .Y (n_508));
  CLKBUFX2 fopt4281(.A (WALLACE_CSA_DUMMY_OP_groupi_n_72), .Y (n_509));
  CLKAND2X2 g4282(.A (n_294), .B (n_319), .Y (n_512));
  NAND2X2 g3912__4283(.A (n_319), .B (n_294), .Y (n_513));
  CLKBUFX2 fopt4286(.A (n_171), .Y (n_518));
  CLKINVX1 fopt4290(.A (n_524), .Y (n_521));
  CLKINVX2 fopt4293(.A (b_reg1[4]), .Y (n_524));
  AND2X1 g4294(.A (a_reg1[2]), .B (b_reg1[5]), .Y (n_528));
  NAND2X1 g4090__4295(.A (b_reg1[5]), .B (a_reg1[2]), .Y (n_529));
  XOR3X1 g4296(.A (n_530), .B (n_174), .C (n_266), .Y (n_531));
  NAND2XL g3(.A (a_reg1[5]), .B (b_reg1[3]), .Y (n_530));
  NAND2XL g4097__4298(.A (a_reg1[5]), .B (b_reg1[3]), .Y (n_532));
  INVXL fopt4299(.A (n_534), .Y (n_535));
  BUFX3 fopt4300(.A (n_537), .Y (n_534));
  INVX2 fopt4301(.A (n_164), .Y (n_537));
  CLKINVX1 fopt4303(.A (n_258), .Y (n_539));
  CLKINVX1 fopt4305(.A (n_215), .Y (n_543));
  INVX1 fopt4307(.A (n_548), .Y (n_547));
  CLKBUFX2 fopt4308(.A (n_549), .Y (n_548));
  CLKINVX1 fopt4309(.A (WALLACE_CSA_DUMMY_OP_groupi_n_42), .Y (n_549));
  CLKINVX1 fopt4310(.A (n_552), .Y (n_551));
  INVX1 fopt4311(.A (n_161), .Y (n_552));
  CLKINVX1 fopt4316(.A (n_559), .Y (n_554));
  INVX1 fopt4317(.A (n_560), .Y (n_559));
  INVX1 fopt4318(.A (n_561), .Y (n_560));
  CLKINVX2 fopt4319(.A (a_reg1[0]), .Y (n_561));
  CLKINVX1 fopt4322(.A (n_566), .Y (n_562));
  CLKINVX1 fopt4327(.A (b_reg1[1]), .Y (n_566));
  INVX2 fopt4337(.A (n_138), .Y (n_581));
  CLKBUFX2 fopt4343(.A (a_reg1[7]), .Y (n_584));
  INVX1 fopt4344(.A (n_175), .Y (n_592));
  CLKBUFX2 fopt4348(.A (a_reg1[6]), .Y (n_594));
  INVX1 fopt4349(.A (n_195), .Y (n_600));
  CLKBUFX2 fopt4350(.A (n_195), .Y (n_601));
  XNOR2X1 g4351(.A (n_603), .B (n_644), .Y (n_604));
  NAND2XL g4352(.A (a_reg1[4]), .B (b_reg1[3]), .Y (n_603));
  NAND2XL g4089__4354(.A (a_reg1[4]), .B (b_reg1[3]), .Y (n_605));
  XNOR3X1 g4356(.A (n_351), .B (n_284), .C (n_375), .Y (n_608));
  MXI2X1 WALLACE_CSA_DUMMY_OP_groupi_g1034__4357(.A (n_611), .B
       (WALLACE_CSA_DUMMY_OP_groupi_n_8), .S0 (n_375), .Y (n_612));
  CLKINVX1 WALLACE_CSA_DUMMY_OP_groupi_g4358(.A
       (WALLACE_CSA_DUMMY_OP_groupi_n_8), .Y (n_611));
  MXI2X1 g3862__4359(.A (n_609), .B (n_351), .S0 (n_284), .Y
       (WALLACE_CSA_DUMMY_OP_groupi_n_8));
  INVXL fopt4360(.A (n_351), .Y (n_609));
  AND2X1 g4365(.A (n_357), .B (n_222), .Y (n_621));
  NAND2XL g4030__4366(.A (n_357), .B (n_222), .Y (n_622));
  DFFRX1 \partial1_reg[1] (.RN (n_1), .CK (clk), .D (n_56), .Q
       (partial1[1]), .QN (n_7));
  DFFRX1 valid_stage1_reg(.RN (n_1), .CK (clk), .D (valid_i), .Q
       (valid_stage1), .QN (n_4));
  DFFRX1 valid_stage2_reg(.RN (n_1), .CK (clk), .D (valid_stage1), .Q
       (valid_stage2), .QN (n_2));
  NAND2BX1 g4375(.AN (n_532), .B (n_169), .Y (n_625));
  XOR3X1 g4376(.A (n_537), .B (n_646), .C (n_539), .Y (n_626));
  XNOR2X1 g4377(.A (n_298), .B (n_349), .Y (n_627));
  XNOR2XL g4379(.A (n_91), .B (n_82), .Y (n_629));
  CLKXOR2X1 g4381(.A (n_605), .B (n_644), .Y (n_631));
  SDFFRHQX1 \partial1_reg[5] (.RN (n_1), .CK (clk), .D (partial1[5]),
       .SI (n_629), .SE (valid_stage1), .Q (partial1[5]));
  SDFFRHQX1 \partial1_reg[7] (.RN (n_1), .CK (clk), .D (partial1[7]),
       .SI (n_92), .SE (valid_stage1), .Q (partial1[7]));
  SDFFRHQX1 \partial2_reg[7] (.RN (n_1), .CK (clk), .D (partial2[7]),
       .SI (n_390), .SE (valid_stage1), .Q (partial2[7]));
  CLKINVX1 fopt4392(.A (n_639), .Y (n_634));
  INVX1 fopt4393(.A (n_640), .Y (n_639));
  CLKBUFX2 fopt4394(.A (b_reg1[5]), .Y (n_640));
  INVX1 fopt4395(.A (WALLACE_CSA_DUMMY_OP_groupi_n_84), .Y (n_642));
  CLKAND2X2 g4396(.A (a_reg1[5]), .B (b_reg1[2]), .Y (n_644));
  CLKAND2X2 g4397(.A (b_reg1[6]), .B (a_reg1[3]), .Y (n_645));
  NAND2BX1 g4398(.AN (n_202), .B (n_214), .Y (n_646));
  NOR2BX1 g4400(.AN (n_543), .B (n_205), .Y (n_648));
  NAND2BX1 g4401(.AN (n_639), .B (n_584), .Y (n_649));
endmodule

